### ISSUE TITLE
Background on this error at: http://sqlalche.me/e/13/e3q8

### ISSUE THREAD

**Issue by juanmallea** [WaTF-Team/WaTF-Bank#4]
al iniciar session se produce el error:

# ./StartServer
Traceback (most recent call last):
  File "manage.py", line 3, in <module>
    from flask_migrate import Migrate, MigrateCommand
ImportError: cannot import name 'MigrateCommand'
Traceback (most recent call last):
  File "manage.py", line 3, in <module>
    from flask_migrate import Migrate, MigrateCommand
ImportError: cannot import name 'MigrateCommand'
Traceback (most recent call last):
  File "manage.py", line 3, in <module>
    from flask_migrate import Migrate, MigrateCommand
ImportError: cannot import name 'MigrateCommand'

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: users
[SQL: SELECT users.id AS users_id, users.username AS users_username, users.password AS users_password, users."accountNo" AS "users_accountNo", users.balance AS users_balance, users.tel AS users_tel, users.token AS users_token, users."citizenID" AS "users_citizenID" 
FROM users 
WHERE users.username = ?
 LIMIT ? OFFSET ?]
[parameters: ('jacob', 1, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)

Por favor su apoyo para solucionar el error

**Comment by WaTF-Team** [comment]
Please use docker instead.
```
docker pull watfteam/watfbank
docker run -d -p 5000:5000 --name watfbank -i -t watfteam/watfbank
```
